# Generated by Django 5.0.7 on 2025-05-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
