# Generated by Django 5.0.7 on 2025-05-14 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_mascota_activa_alter_mascota_foto_and_more'),
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenDiagnostica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.ImageField(upload_to='imagenes_diagnosticas/%Y/%m/%d/')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='clientes.mascota')),
            ],
            options={
                'verbose_name': 'Imagen Diagnóstica',
                'verbose_name_plural': 'Imágenes Diagnósticas',
                'ordering': ['-fecha'],
            },
        ),
    ]
