# Generated by Django 5.0.7 on 2025-05-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_imagendiagnostica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagendiagnostica',
            name='archivo',
            field=models.FileField(upload_to='imagenes_diagnosticas/%Y/%m/%d/'),
        ),
    ]
