# Generated by Django 5.2.1 on 2025-06-11 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_alter_mascota_activa_alter_mascota_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Usuario')),
                ('password', models.CharField(max_length=128, verbose_name='Contraseña')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último acceso')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acceso_portal', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Acceso Portal Cliente',
                'verbose_name_plural': 'Accesos Portal Clientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
